### ISSUE TITLE
Unable to run deploy-server.js with Yarn3

### ISSUE THREAD

**Issue by carbontwelve** [ferdinandfrank/cdk-nuxt#9]
I've been successfully using this stack in my monorepo however I have had to "vendor" its content within my repository because the `install-layer` commands use a `--modules-folder` flag which doesn't appear to exist in the version 3.6.3 of Yarn that I am using.

My proposed solution would be to make use of the bundling ability of `Code.fromAsset` to compile the requirements directly, for example:

```ts
Code.fromAsset(path.join(__dirname, '../../functions/assets-cleanup'), {
  bundling: {
    image: Runtime.NODEJS_20_X.bundlingImage,
    local: {
      tryBundle(outputDir) {
          // Build and copy result to outputDir
      },
    }
  }
})
```

I'll be attempting to write this over the next couple of days and provide a PR.

**Comment by ferdinandfrank** [comment]
@carbontwelve Thank you for this hint! I'll try to check the implementation via `Code.fromAsset` soon and add it, if it's working. If you are already working on a PR, feel free to submit it.

**Comment by ferdinandfrank** [comment]
@carbontwelve I was able to use the bundling ability of `Code.fromAsset` but still failed to get it working for Yarn Classic (v1) and Yarn Berry (v>=2) due to the requirement of installing the dependencies (`node_modules`) for the layers of the package's infrastructure functions.
When initialising the dependencies, i.e., creating the `yarn.lock` file, using Yarn Classic a bundling of `Code.fromAsset` was not possible due to the fact that the `yarn.lock` file would have been modified and vice versa when initialising the dependencies with Yarn Berry. The background of this is that both Yarn versions differentially manage their dependencies making a mix of both version incompatible for this package.

However, to support Yarn Classic and Yarn Berry simultaneously (as well as other package managers), I decided to benefit from the integrated AWS SDKs that are automatically bundled with Lambda which makes the installation of the layers for the package's functions obsolete.
The only drawback is the fact that the package's infrastructure functions do not use a fixed AWS SDK version but rather the bundled versions of AWS Lambda. Since these functions are pretty simple and only use basic features of these SDKs, these drawbacks can be neglected on my opinion.

Therefore, starting with version `2.3.1` the package can now be used with Yarn >= 2.
